EmpresTech/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmpresTech.Models;

public class EmprestimosModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Digite o nome do recebedor!")]
    public string Recebedor { get; set; }

    [Required(ErrorMessage = "Digite o nome do fornecedor!")]
    public string Fornecedor { get; set; }

    [Required(ErrorMessage = "Digite o nome do livro!")]
    public string LivroEmprestado { get; set; }

    public DateTime DataUltimaAtualizacao { get; set; }
}

EmpresTech/Models/ErrorViewModel.cs
namespace EmpresTech.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EmpresTech/Models/ResponseModel.cs
namespace EmpresTech.Models;

public class ResponseModel<T>
{
    public T? Dados { get; set; }

    public string Mensagem { get; set; } = String.Empty;

    public bool Status { get; set; } = true;
}

EmpresTech/Models/UsuarioModel.cs
namespace EmpresTech.Models;

public class UsuarioModel
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Sobrenome { get; set; }

    public string Email { get; set; }

    public byte[] SenhaHash { get; set; }

    public byte[] SenhaSalt { get; set; }
}

EmpresTech/Controllers/EmprestimoController.cs
using System.Data;
using ClosedXML.Excel;
using EmpresTech.Data;
using EmpresTech.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmpresTech.Controllers;

public class EmprestimoController : Controller
{
    private readonly ApplicationDbContext _db;

    public EmprestimoController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos;
        return View(emprestimos);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Editar(int? id)
    {
        if (id == null || id == 0)
            return NotFound();

        EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

        if (emprestimo == null)
            return NotFound();

        return View(emprestimo);
    }

    [HttpGet]
    public IActionResult Excluir(int? id)
    {
        if (id == null || id == 0)
            return NotFound();

        EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);

        if (emprestimo == null)
            return NotFound();

        return View(emprestimo);
    }

    public IActionResult Exportar()
    {
        var dados = GetDados();
        using (XLWorkbook workbook = new XLWorkbook())
        {
            workbook.AddWorksheet(dados, "Dados Empréstimos");
            using (MemoryStream ms = new MemoryStream())
            {
                workbook.SaveAs(ms);
                return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spredsheetml.sheet",
                    "Emprestimo.xls");
            }
        }
    }

    private DataTable GetDados()
    {
        DataTable dataTable = new DataTable();
        dataTable.TableName = "Dados empréstimos";
        dataTable.Columns.Add("Recebedor", typeof(string));
        dataTable.Columns.Add("Fornecedor", typeof(string));
        dataTable.Columns.Add("Livro", typeof(string));
        dataTable.Columns.Add("Data empréstimo", typeof(DateTime));

        var dados = _db.Emprestimos.ToList();
        if (dados.Count > 0)
        {
            dados.ForEach(emprestimo =>
            {
                dataTable.Rows.Add(emprestimo.Recebedor, emprestimo.Fornecedor, emprestimo.LivroEmprestado,
                    emprestimo.DataUltimaAtualizacao);
            });
        }

        return dataTable;
    }

    [HttpPost]
    public IActionResult Cadastrar(EmprestimosModel emprestimos)
    {
        if (ModelState.IsValid)
        {
            emprestimos.DataUltimaAtualizacao = DateTime.Now;

            _db.Emprestimos.Add(emprestimos);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

            return RedirectToAction("Index");
        }

        TempData["MensagemErro"] = "Ocorreu algum erro ao realizar o cadastro!";

        return View();
    }

    [HttpPost]
    public IActionResult Editar(EmprestimosModel emprestimo)
    {
        if (ModelState.IsValid)
        {
            var emprestimoDB = _db.Emprestimos.Find(emprestimo.Id);

            emprestimoDB.Fornecedor = emprestimo.Fornecedor;
            emprestimoDB.Recebedor = emprestimo.Recebedor;
            emprestimoDB.LivroEmprestado = emprestimo.LivroEmprestado;

            _db.Emprestimos.Update(emprestimoDB);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Edição realizada com sucesso!";

            return RedirectToAction("Index");
        }

        TempData["MensagemErro"] = "Ocorreu algum erro ao realizar a edição!";

        return View(emprestimo);
    }

    [HttpPost]
    public IActionResult Excluir(EmprestimosModel emprestimo)
    {
        if (emprestimo == null)
        {
            TempData["MensagemErro"] = "Ocorreu algum erro ao realizar o cadastro!";
            return NotFound();
        }

        _db.Emprestimos.Remove(emprestimo);
        _db.SaveChanges();

        TempData["MensagemSucesso"] = "Remoção realizada com sucesso!";


        return RedirectToAction("Index");
    }
}

EmpresTech/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EmpresTech.Models;

namespace EmpresTech.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

EmpresTech/Controllers/LoginController.cs
using EmpresTech.Dto;
using EmpresTech.Services.LoginService;
using Microsoft.AspNetCore.Mvc;

namespace EmpresTech.Controllers;

public class LoginController : Controller
{
    private readonly ILoginInterface _loginInterface;

    public LoginController(ILoginInterface loginInterface)
    {
        _loginInterface = loginInterface;
    }

    // GET
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Registrar()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Registrar(UsuarioRegisterDto usuarioRegisterDto)
    {
        if (ModelState.IsValid)
        {
            var usuario = await _loginInterface.RegistrarUsuario(usuarioRegisterDto);
            if (usuario.Status)
            {
                TempData["MensagemSucesso"] = usuario.Mensagem;
            }
            else
            {
                TempData["MensagemErro"] = usuario.Mensagem;
                return View(usuarioRegisterDto);
            }

            return RedirectToAction("Index");
        }
        else
        {
            return View(usuarioRegisterDto);
        }
    }
}

EmpresTech/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Cadastrar Empréstimo";
}
<div class="container p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1>Cadastro de Empréstimos</h1>
    </div>
    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">

        <div class="mb-4">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-4">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-4">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="livro" placeholder="Qual é o nome do livro?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>

        </div>
    </form>
</div>

EmpresTech/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar Empréstimo";
}
<div class="container p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1>Edição de Empréstimos</h1>
    </div>
    <form method="post" asp-controller="Emprestimo" asp-action="Editar">

        <input type="hidden" asp-for="Id"/>

        <div class="mb-4">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-4">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-4">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="livro" placeholder="Qual é o nome do livro?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>

        </div>
    </form>
</div>

EmpresTech/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Excluir Empréstimo";
}
<div class="container p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1>Excluir Empréstimos</h1>
    </div>
    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">

        <input type="hidden" asp-for="Id"/>

        <h2>Tem certeza que deseja excluir o registo abaixo?</h2>

        <div class="mb-4">
            <label for="Recebedor" class="form-label">Recebedor</label>
            <input type="text" class="form-control" asp-for="Recebedor" disabled id="recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-4">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" disabled id="fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-4">
            <label for="Livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" disabled id="livro" placeholder="Qual é o nome do livro?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>

        </div>
    </form>
</div>

EmpresTech/Views/Emprestimo/Index.cshtml
@{
    ViewData["title"] = "Empréstimos";
}

@model IEnumerable<EmprestimosModel>

<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos de Livros</h1>

        <div>
            <a class="btn btn-primary mx-2" asp-controller="Emprestimo" asp-action="Exportar"><i class="bi bi-cloud-plus-fill mx-2"></i>Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-cloud-plus-fill mx-2"></i>Cadastrar novo empréstimo</a>

        </div>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <table id="emprestimos" class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Data Empréstimo</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @if (Model != null)
        {
            @foreach (var emprestimo in Model)
            {
                <tr>
                    <td>@emprestimo.Recebedor</td>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.DataUltimaAtualizacao</td>
                    <td>
                        <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-fill mx-2"></i>Editar</a>
                        <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill mx-2"></i>Excluir</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

EmpresTech/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center mt-5">
    <h1 class="display-4">Empréstimos de livros online</h1>
    <p>"Descubra, empreste e leia – sua biblioteca online sempre ao seu alcance."</p>

    <img class="w-50 mt-4" src="assets/book.png"/>

</div>

EmpresTech/Views/Login/Index.cshtml
@{
    ViewData["title"] = "Login";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-light" role="alert">
        @TempData["MensagemErro"]
    </div>
}

<div class="container">
    <div class="row align-items-center my-5">
        <div class="col-sm-6">
            <img src="assets/book.png" style="width: 560px"/>
        </div>
        <form class="col-sm-6">
            <div class="mb-4">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Digite seu email">
            </div>
            <div class="mb-4">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" class="form-control" id="senha" placeholder="Digite sua senha">
            </div>
            <div class="d-flex flex-row mt-5 justify-content-center gap-3">
                <button type="submit" class="btn btn-primary w-50">Entrar</button>
                <a asp-action="Registrar" asp-controller="Login" class="btn w-50">Cadastrar</a>
            </div>
        </form>
    </div>
</div>

EmpresTech/Views/Login/Registrar.cshtml
@model EmpresTech.Dto.UsuarioRegisterDto

@{
    ViewData["title"] = "Registrar";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-light" role="alert">
        @TempData["MensagemErro"]
    </div>
}

<div asp-validation-summary="All" class="text-danger"></div>

<div class="container mt-5">
    <h2>Cadastro de Usuários</h2>
    <form asp-action="Registrar" asp-controller="Login" method="post">
        <div class="mb-4">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" asp-for="Nome" id="nome" placeholder="Digite seu nome">
        </div>
        <div class="mb-4">
            <label for="sobrenome" class="form-label">Sobrenome</label>
            <input type="text" class="form-control" asp-for="Sobrenome" id="sobrenome" placeholder="Digite seu sobrenome">
        </div>
        <div class="mb-4">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" asp-for="Email" id="email" placeholder="Digite seu email">
        </div>
        <div class="mb-4">
            <label for="senha" class="form-label">Senha</label>
            <input type="password" class="form-control" asp-for="Senha" id="senha" placeholder="Digite sua senha">
        </div>
        <div class="mb-4">
            <label for="confirmaSenha" class="form-label">Confirmar senha</label>
            <input type="password" class="form-control" asp-for="ConfirmaSenha" id="confirmaSenha" placeholder="Confirme sua senha">
        </div>
        <div class="d-flex justify-content-center align-items-center gap-4">
            <button type="submit" class="btn btn-primary w-25">Cadastrar</button>
            <a asp-action="Index" asp-controller="Login" class="btn w-25">Voltar</a>
        </div>
    </form>
</div>

EmpresTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EmpresTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/EmpresTech.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand text-light text-decoration-underline" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-terminal-fill mx-1"></i>EmpresTech</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-book-half mx-2"></i>Empréstimos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted bg-primary bottom-0 position-fixed w-100">
    <div class="container d-flex text-light justify-content-center align-items-center">
        &copy; 2024 - YanGraim <i class="bi bi-code-slash mx-2"></i>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>